env:
  global:
    # Use pip cache for wheels
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
before_install:
  - sudo apt-get install -y libasound2-dev libmpg123-dev libatlas-base-dev
  - sudo sh install_kaldi.sh
  - pip install --upgrade pip
  # Build wheels for anything that is not in PyPI (e.g. py-kaldi-asr)
  - pip wheel -r requirements.txt
  - pip install cython
language: python
python:
  - 3.7
cache: pip
dist: bionic
sudo: true
script:
  - sh .travis_build_nlu_engines.sh
  - sudo mkdir -p /run/systemd/timesync/ && sudo touch /run/systemd/timesync/synchronized
  - coverage run -m pytest
  - bash <(curl -s https://codecov.io/bash)
addons:
  postgresql: "10"
services:
  - postgresql
before_script:
  - psql -U postgres -d postgres -c "CREATE USER pynab; ALTER ROLE pynab CREATEDB;"
