before_install:
  - sudo apt-get install -y libasound2-dev libmpg123-dev libatlas-base-dev
  - sudo sh install_kaldi.sh
  - pip install cython
language: python
python:
  - 3.7
dist: bionic
sudo: true
script:
  - sh /home/travis/build/nabaztag2018/pynab/.travis_build_nlu_engines.sh
  - mkdir -p /run/systemd/timesync/ && touch /run/systemd/timesync/synchronized
  - pytest
addons:
  postgresql: "10"
services:
  - postgresql
before_script:
  - psql -U postgres -d postgres -c "CREATE USER pynab; ALTER ROLE pynab CREATEDB;"
