contact_links:
  - name: ğŸ¤” Have questions or need support with pynab?
    url: https://github.com/nabaztag2018/pynab/discussions
    about: Please get in touch on the Discussions page!
  - name: ğŸ’¬ Meet the community and live chat about your Nabaztag or TagTagTag!
    url: https://dsc.gg/nabaztagtagtag
    about: Let's chat with each others on Discord!
  - name: ğŸ—£ Have questions or need support with Nabaztag or TagTagTag?
    url: http://tagtagtag.fr/forum/
    about: Please get in touch on the TagTagTag Community Forums!
